export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const SET_SELECTED_SORT = 'SET_SELECTED_SORT';
export const SET_AVAILABLE_SORTS = 'SET_AVAILABLE_SORTS';
export const SET_AVAILABLE_PRICE_FILTER = 'SET_AVAILABLE_PRICE_FILTER';
export const SET_PRICE_FILTER = 'SET_PRICE_FILTER';
export const FETCH_PRODUCTS_REQUEST = 'FETCH_PRODUCTS_REQUEST';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';
